# Site settings
author: Jennifer Grace Prince
title: Jennifer's Software Engineering School Blog
header-img: img/home-bg.png
email: jennifergraceprince@gmail.com
copyright_name: Jennifer Grace Prince
description: > # this means to ignore newlines until "baseurl:"
  A creative soul learns to code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jennifergraceprince

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
